name: "CF Deploy SAP BTP"
description: Deploy an .mtar file built for SAP BTP using Cloud Foundry CLI.
branding:
  icon: "upload-cloud"
  color: "red"
inputs:
  MTAR_PATH:
    description: Path to your MTA file.
    required: true
  API:
    description: Cloud Foundry API endpoint.
    required: true
  USER:
    description: Cloud Foundry username.
    required: true
  PASSWORD:
    description: Cloud Foundry password.
    required: true
  ORG:
    description: Cloud Foundry organization.
    required: true
  SPACE:
    description: Cloud Foundry space to deploy to.
    required: true

runs:
  using: docker
  image: Dockerfile